apiVersion: batch/v1
kind: Job
metadata:
  name: alembic-migrate  # remplacé dynamiquement par le script
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: alembic
          image: backend-dev:latest   # remplacé dynamiquement par le script
          imagePullPolicy: IfNotPresent
          command: ["alembic", "-c", "alembic.ini", "upgrade", "head"]
          envFrom:
            - secretRef:
                name: postgres-secret
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_URL  # tu peux créer cette clé dans le secret avec la full URL
