apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  POSTGRES_USER: cG9zdGdyZXM=       # "postgres" encodé en base64
  POSTGRES_PASSWORD: c2VjdXJlcGFzcw== # "securepass" encodé en base64
  POSTGRES_DB: ZWNvbW1lcmNl         # "ecommerce" encodé en base64
