"""Add order status enum

Revision ID: 1242839c3071
Revises: ebeea5ee348c
Create Date: 2025-11-03 17:04:31.863808

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1242839c3071'
down_revision: Union[str, Sequence[str], None] = 'ebeea5ee348c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.alter_column('orders', 'status',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('pending', 'paid', 'shipped', 'delivered', 'cancelled', name='orderstatus'),
               existing_nullable=True)
    op.alter_column('orders', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('orders', 'status',
               existing_type=sa.Enum('pending', 'paid', 'shipped', 'delivered', 'cancelled', name='orderstatus'),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_column('orders', 'updated_at')
    # ### end Alembic commands ###
