"""Add shipping columns to orders

Revision ID: ebeea5ee348c
Revises: 5f6e95434d53
Create Date: 2025-11-03 09:51:21.601139

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ebeea5ee348c'
down_revision: Union[str, Sequence[str], None] = '5f6e95434d53'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('shipping_name', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('shipping_address', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('shipping_city', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('shipping_postal_code', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('shipping_phone', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('stripe_session_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'stripe_session_id')
    op.drop_column('orders', 'shipping_phone')
    op.drop_column('orders', 'shipping_postal_code')
    op.drop_column('orders', 'shipping_city')
    op.drop_column('orders', 'shipping_address')
    op.drop_column('orders', 'shipping_name')
    # ### end Alembic commands ###
